version: '3.3'

services:
  postgresql:
    image: postgres:13.3
    container_name: db
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=belet_news
    volumes:
      - /var/lib/docker/data/database:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: storage
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=AHMET
      - MINIO_ROOT_PASSWORD=Ah25101996!
      - MINIO_ACCESS_KEY=AHMET
      - MINIO_SECRET_KEY=BELETNEWS
    volumes:
      - /var/lib/docker/data/storage:/data
    command: server /data

  parser:
    build: ./
    restart: on-failure
    depends_on:
      - postgresql
      - minio

networks:
  default:
    driver: bridge
